version: '3'

volumes:
  logs:
    driver: local

services:
  php:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    working_dir: /var/www/html
    ports:
      - 8055:443
      - 80:80
    volumes:
      - .:/var/www/html
      - .docker/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3333:3306
    volumes:
      - .docker/mysql/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=public
    command: --sql_mode="NO_ENGINE_SUBSTITUTION"
